import asyncio
import uuid
from backend.database import init_db, get_db_connection
from backend.models import DisinformationTrend
import json

# Real-world data gathered from web search (2024-2025 trends)
REAL_TRENDS = [
    DisinformationTrend(
        id=str(uuid.uuid4()),
        topic="Flat Earth Theory",
        description="The conspiracy theory that the Earth is a flat plane, often claiming NASA fabricates space imagery.",
        severity="Medium",
        common_phrases=[
            "Show me the curve", 
            "Water always seeks its level", 
            "NASA lies", 
            "Antarctic ice wall", 
            "Gravity is a hoax",
            "The Earth is motionless",
            "Firmament"
        ],
        counter_arguments=[
            "Satellite imagery and GPS systems rely on spherical geometry", 
            "Gravity's consistent pull towards the center of mass", 
            "Circumnavigation of the globe",
            "Disappearance of ships hull-first over the horizon",
            "Star constellations changing based on latitude"
        ],
        sources=["YouTube (Flat Earth Society)", "Facebook Groups", "TikTok"]
    ),
    DisinformationTrend(
        id=str(uuid.uuid4()),
        topic="Anti-Vaccine Narratives",
        description="Misinformation regarding vaccine safety, often alleging hidden agendas or harmful ingredients.",
        severity="High",
        common_phrases=[
            "Medical freedom", 
            "Big Pharma", 
            "Vaccines cause autism", 
            "DNA alteration", 
            "Microchips", 
            "Spike protein cytotoxicity",
            "Experimental gene therapy",
            "Depopulation agenda"
        ],
        counter_arguments=[
            "Extensive clinical trial data proving safety", 
            "Peer-reviewed scientific studies debunking autism links", 
            "mRNA vaccines do not alter DNA",
            "Historical success in eradicating polio and smallpox"
        ],
        sources=["Telegram Channels", "Alternative Health Blogs", "Twitter/X"]
    ),
    DisinformationTrend(
        id=str(uuid.uuid4()),
        topic="Election Denialism",
        description="False claims that democratic elections are rigged or manipulated by external actors.",
        severity="High",
        common_phrases=[
            "Stop the steal", 
            "Rigged election", 
            "Dead people voting", 
            "Dominion voting machines", 
            "Ballot harvesting",
            "Mules"
        ],
        counter_arguments=[
            "Multiple independent audits confirming results", 
            "Lack of evidence in court cases", 
            "Security protocols of voting machines"
        ],
        sources=["Truth Social", "Rumble", "Partisan News Outlets"]
    ),
    DisinformationTrend(
        id=str(uuid.uuid4()),
        topic="Deep State / QAnon",
        description="Theories alleging a secret cabal of elites runs the government and engages in heinous acts.",
        severity="High",
        common_phrases=[
            "The Great Awakening", 
            "Trust the plan", 
            "Where we go one we go all", 
            "WWG1WGA", 
            "Adrenochrome", 
            "Cabal",
            "Deep State"
        ],
        counter_arguments=[
            "Lack of credible evidence for a centralized cabal", 
            "Failed predictions (e.g., 'The Storm')", 
            "Debunking of specific claims by independent journalists"
        ],
        sources=["8kun", "Telegram", "Gab"]
    ),
    DisinformationTrend(
        id=str(uuid.uuid4()),
        topic="Climate Change Denial",
        description="Claims that climate change is a hoax or natural cycle, dismissing human impact.",
        severity="High",
        common_phrases=[
            "Climate hoax", 
            "CO2 is plant food", 
            "Global cooling", 
            "Weather modification", 
            "Chemtrails"
        ],
        counter_arguments=[
            "Overwhelming scientific consensus (99%)", 
            "Measurable rise in global temperatures and sea levels", 
            "Correlation with industrial greenhouse gas emissions"
        ],
        sources=["Fossil Fuel Lobby Groups", "YouTube Commentaries", "Twitter/X"]
    ),
     DisinformationTrend(
        id=str(uuid.uuid4()),
        topic="Dead Internet Theory",
        description="The belief that the majority of internet content is now generated by bots and AI, not humans.",
        severity="Low",
        common_phrases=[
            "Dead internet", 
            "Bot activity", 
            "AI generated content", 
            "Echo chamber"
        ],
        counter_arguments=[
            "While bot activity exists, vast human interaction remains verifiable", 
            "Traffic analysis shows human user base"
        ],
        sources=["Reddit", "Tech Forums", "TikTok"]
    )
]

def seed():
    print("Initializing database...")
    init_db()
    
    conn = get_db_connection()
    cursor = conn.cursor()
    
    # Clear existing data to ensure no stale/mock data remains
    cursor.execute("DELETE FROM trends")
    
    print("Seeding real-world trends...")
    for trend in REAL_TRENDS:
        cursor.execute(
            "INSERT INTO trends (id, topic, description, severity, common_phrases, counter_arguments, sources) VALUES (?, ?, ?, ?, ?, ?, ?)",
            (
                trend.id,
                trend.topic,
                trend.description,
                trend.severity,
                json.dumps(trend.common_phrases),
                json.dumps(trend.counter_arguments),
                json.dumps(trend.sources)
            )
        )
        print(f"Added: {trend.topic}")
    
    conn.commit()
    conn.close()
    print("Database seeded successfully.")

if __name__ == "__main__":
    seed()
